//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal
    {
        public int id { get; set; }
        public int idState { get; set; }
        public string nombre { get; set; }
        public int patas { get; set; }
        public byte[] picture { get; set; }
    }
}
